### ISSUE TITLE
Translate “03-05 Flow control”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#10]
**File:** `manuscript/03-05-Flow-control.md`
**Branch:** `03-05-flow-control`
**Original:** [`src/language-basics.adoc#flow-control`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#flow-control)

**Comment by roman01la** [comment]
Working in this section

**Comment by denysdovhan** [comment]
Translated
