### ISSUE TITLE
Translate “03-06 Truthiness”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#11]
**File:** `manuscript/03-06-Truthiness.md`
**Branch:** `03-06-truthiness`
**Original:** [`src/language-basics.adoc#truthiness`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#truthiness)

**Comment by roman01la** [comment]
Working in this section

**Comment by denysdovhan** [comment]
Translate
