### ISSUE TITLE
Translate “03-07 Locals, Blocks, and Loops”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#12]
**File:** `manuscript/03-07-Locals-Blocks-and-Loops.md`
**Branch:** `03-07-locals-blocks-and-loops`
**Original:** [`src/language-basics.adoc#locals-blocks-and-loops`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#locals-blocks-and-loops)

**Comment by roman01la** [comment]
Working in this section
