### ISSUE TITLE
Translate “03-08 Collection types”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#13]
**File:** `manuscript/03-08-Collection-types.md`
**Branch:** `03-08-collection-types`
**Original:** [`src/language-basics.adoc#collection-types`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#collection-types)

**Comment by AMashoshyna** [comment]
working on this section

**Comment by AMashoshyna** [comment]
@roman01la а seqables можно перевести как "спископодібні"?

**Comment by roman01la** [comment]
@AMashoshyna судя по тексту — да, но я уточню у автора книги.

**Comment by roman01la** [comment]
@AMashoshyna ответ автора оригинала:
> I think that is: sequables are collections that can be converted in to seq
or can be adapted into the seq abstraction

так что «спископодібні» наверное подходит

**Comment by denysdovhan** [comment]
@AMashoshyna дай будь-лайска свою пошту.

**Comment by AMashoshyna** [comment]
@denysdovhan a.mashoshyna@gmail.com

@roman01la спасибо!
