### ISSUE TITLE
Translate “03-09 Destructuring”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#14]
**File:** `manuscript/03-09-Destructuring.md`
**Branch:** `03-09-destructuring`
**Original:** [`src/language-basics.adoc#destructuring`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#destructuring)

**Comment by roman01la** [comment]
Working on this one
