### ISSUE TITLE
Translate “03-10 Threading Macros”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#15]
**File:** `manuscript/03-10-Threading-Macros.md`
**Branch:** `03-10-threading-macros`
**Original:** [`src/language-basics.adoc#threading-macros`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#threading-macros)

**Comment by roman01la** [comment]
working on it
