### ISSUE TITLE
Translate “03-11 Reader Conditionals”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#16]
**File:** `manuscript/03-11-Reader-Conditionals.md`
**Branch:** `03-11-reader-conditionals`
**Original:** [`src/language-basics.adoc#reader-conditionals`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#reader-conditionals)

**Comment by roman01la** [comment]
working on it
