### ISSUE TITLE
Translate “03-13 Abstractions and Polymorphism”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#18]
**File:** `manuscript/03-13-Abstractions-and-Polymorphism.md`
**Branch:** `03-13-abstractions-and-polymorphism`
**Original:** [`src/language-basics.adoc#abstractions-and-polymorphism`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#abstractions-and-polymorphism)

**Comment by roman01la** [comment]
working on this
