### ISSUE TITLE
Translate “03-15 Host interoperability”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#20]
**File:** `manuscript/03-15-Host-interoperability.md`
**Branch:** `03-15-host-interoperability`
**Original:** [`src/language-basics.adoc#host-interoperability`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#host-interoperability)

**Comment by roman01la** [comment]
working on this section

**Comment by denysdovhan** [comment]
Translated and merged.
