### ISSUE TITLE
Translate “03-16 State management”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#21]
**File:** `manuscript/03-16-State-management.md`
**Branch:** `03-16-state-management`
**Original:** [`src/language-basics.adoc#state-management`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#state-management)

**Comment by roman01la** [comment]
Working on this

**Comment by denysdovhan** [comment]
Translated and merged
