### ISSUE TITLE
Translate “04-01 Getting Started with the Compiler”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#23]
**File:** `manuscript/04-01-Getting-Started-with-the-Compiler.md`
**Branch:** `04-01-getting-started`
**Original:** [`src/compiler.adoc#getting-started-with-the-compiler`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/compiler.adoc#getting-started-with-the-compiler)

**Comment by AMashoshyna** [comment]
working on this one

**Comment by AMashoshyna** [comment]
@denysdovhan please reassign this section to @roman01la - he started already

**Comment by denysdovhan** [comment]
@AMashoshyna feel free to do it. You have permissions.

**Comment by denysdovhan** [comment]
Translated and merged.
