### ISSUE TITLE
Translate “04-02 Working with the REPL”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#24]
**File:** `manuscript/04-02-Working-with-the-REPL.md`
**Branch:** `04-02-repl`
**Original:** [`src/compiler.adoc#working-with-the-repl`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/compiler.adoc#working-with-the-repl)

**Comment by AMashoshyna** [comment]
working on this one

**Comment by denysdovhan** [comment]
Translated and merged.
