### ISSUE TITLE
Translate “04-03 The Closure Library”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#25]
**File:** `manuscript/04-03-The-Closure-Library.md`
**Branch:** `04-03-closure-library`
**Original:** [`src/compiler.adoc#the-closure-library`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/compiler.adoc#the-closure-library)

**Comment by roman01la** [comment]
working on this

**Comment by denysdovhan** [comment]
Translated and merged.
