### ISSUE TITLE
Translate “04-04 Dependency management”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#26]
**File:** `manuscript/04-04-Dependency-management.md`
**Branch:** `04-04-dependency-management`
**Original:** [`src/compiler.adoc#dependency-management`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/compiler.adoc#dependency-management)

**Comment by roman01la** [comment]
working on this
