### ISSUE TITLE
Translate “04-05 External dependencies”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#27]
**File:** `manuscript/04-05-External-dependencies.md`
**Branch:** `04-05-external-dependencies`
**Original:** [`src/compiler.adoc#external-dependencies`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/compiler.adoc#external-dependencies)

**Comment by AMashoshyna** [comment]
working on this one

**Comment by roman01la** [comment]
@AMashoshyna sorry, I'm already working on this :)

**Comment by AMashoshyna** [comment]
@roman01la ok :)
