### ISSUE TITLE
Translate “04-06 Unit testing”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#28]
**File:** `manuscript/04-05-Unit-testing.md`
**Branch:** `04-05-unit-testing`
**Original:** [`src/compiler.adoc#unit-testing`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/compiler.adoc#unit-testing)

**Comment by roman01la** [comment]
working on this
