### ISSUE TITLE
Translate ”01 About this book”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#3]
**File:** `manuscript/01-About-this-book.md`
**Branch:** `01-about-this-book`
**Original:** [`src/index.adoc#about-this-book`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/index.adoc#about-this-book)

**Comment by AMashoshyna** [comment]
I'd like to translate this piece

**Comment by roman01la** [comment]
@AMashoshyna Hey. Thanks. I'm already working on this section. In fact it's done, but requires review. Would you like to join the review process?

**Comment by AMashoshyna** [comment]
@roman01la sure! what do I do?

**Comment by roman01la** [comment]
working on it

**Comment by roman01la** [comment]
@AMashoshyna you can translate a different chapter

**Comment by AMashoshyna** [comment]
@roman01la ok

**Comment by denysdovhan** [comment]
Closed in #38
