### ISSUE TITLE
Translate “05-01 Transducers”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#30]
**File:** `manuscript/05-01-Transducers.md`
**Branch:** `05-01-transducers`
**Original:** [`src/language-advanced.adoc#transducers`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-advanced.adoc#transducers)

**Comment by roman01la** [comment]
working on this

**Comment by denysdovhan** [comment]
@roman01la any progress on this?

**Comment by denysdovhan** [comment]
Published!
