### ISSUE TITLE
Translate “05-03 Metadata”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#32]
**File:** `manuscript/05-03-Metadata.md`
**Branch:** `05-03-metadata`
**Original:** [`src/language-advanced.adoc#metadata`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-advanced.adoc#metadata)

**Comment by AMashoshyna** [comment]
working on it

**Comment by AMashoshyna** [comment]
@denysdovhan I'll finish this one

**Comment by denysdovhan** [comment]
Published!
