### ISSUE TITLE
Translate “05-04 Core protocols”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#33]
**File:** `manuscript/05-04-Core-protocols.md`
**Branch:** `05-04-core-protocols`
**Original:** [`src/language-advanced.adoc#core-protocols`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-advanced.adoc#core-protocols)

**Comment by standemchuk** [comment]
working on this section

**Comment by AMashoshyna** [comment]
@standemchuk Hi! Are you working on this section or should I take it?

**Comment by standemchuk** [comment]
@AMashoshyna take it please, didn’t have time to work on it

**Comment by AMashoshyna** [comment]
@standemchuk ok, thanks for quick reply!

**Comment by AMashoshyna** [comment]
@denysdovhan I'll finish this one

**Comment by denysdovhan** [comment]
Done!
