### ISSUE TITLE
Translate “05-05 CSP (with core.async)”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#34]
**File:** `manuscript/05-05-CSP.md`
**Branch:** `05-05-csp`
**Original:** [`src/language-advanced.adoc#csp-with-coreasync`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-advanced.adoc#csp-with-coreasync)

**Comment by roman01la** [comment]
I'm on it

**Comment by kpi-zpi-72** [comment]
I could take this one. @roman01la is it ok ?

**Comment by AMashoshyna** [comment]
I'll take it, ok? @roman01la

**Comment by denysdovhan** [comment]
@roman01la said he isn’t going to finish this chapter.

**Comment by denysdovhan** [comment]
Done by #92
