### ISSUE TITLE
Translate “03-01 First steps with Lisp syntax”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#6]
**File:** `manuscript/03-01-First-steps-with-List-syntax.md`
**Branch:** `03-01-first-steps-lisp`
**Original:** [`src/language-basics.adoc#first-steps-with-lisp-syntax`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#first-steps-with-lisp-syntax)

**Comment by AMashoshyna** [comment]
working on this section

**Comment by denysdovhan** [comment]
Translated
