### ISSUE TITLE
Translate “03-02 The base data types”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#7]
**File:** `manuscript/03-02-The-base-data-types.md`
**Branch:** `03-02-base-data-types`
**Original:** [`src/language-basics.adoc#the-base-data-types`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#the-base-data-types)

**Comment by roman01la** [comment]
working on this section

**Comment by denysdovhan** [comment]
Translated
