### ISSUE TITLE
Translate “03-03 Vars”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#8]
**File:** `manuscript/03-03-Vars.md`
**Branch:** `03-03-vars`
**Original:** [`src/language-basics.adoc#vars`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#vars)

**Comment by roman01la** [comment]
Working on this section

**Comment by denysdovhan** [comment]
Translated
