### ISSUE TITLE
Book downloads via gitbooks.com not working

### ISSUE THREAD

**Issue by andrewkharook** [LambdaBooks/clojurescript-unraveled#80]
Якщо спобувати завантажити книгу, використовуючи будь-яке з посилань на [цій сторінці](http://lambdabooks.com/clojurescript-unraveled/), то отримуємо помилку 404 з повідомленням "E-Books downloads have been disabled for this book" на сайті gitbooks.com

**Comment by denysdovhan** [comment]
Виправилено! Тепер посилання працюють як слід.

Дякуємо, що повідомили!
