### ISSUE TITLE
Translate “03-04 Functions”

### ISSUE THREAD

**Issue by denysdovhan** [LambdaBooks/clojurescript-unraveled#9]
**File:** `manuscript/03-04-Functions.md`
**Branch:** `03-04-functions`
**Original:** [`src/language-basics.adoc#functions`](https://github.com/funcool/clojurescript-unraveled/blob/master/src/language-basics.adoc#functions)

**Comment by AMashoshyna** [comment]
started working on this section

**Comment by denysdovhan** [comment]
Translated
